version: '3.1'
services:
  web:
    build: .
    container_name: java-security-jwt
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=817b62
      - SPRING_JWT_SECRET=mikarte
  db:
    image: postgres:14-alpine
    container_name: test-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=817b62