CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    CONSTRAINT unique_name UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS messages(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) REFERENCES users(name) NOT NULL,
    message VARCHAR(500) NOT NULL
);